version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image on `date`"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  
      - echo "Execute the Docker image on `date`"
      - docker run -p 8888:8888 -d $IMAGE_REPO_NAME:$IMAGE_TAG
      - sleep 15s
      - echo "Testing the Docker container on `date`"
      - curl http://localhost:8888
      - TESTING_OUTPUT=$(grep -ci $TESTING_PARAMETER output.html)
      - if [ $TESTING_OUTPUT -eq "0" ]; then exit 1 ; else echo "Testing SUCCESSFULLY on `date`" ; fi
  post_build:
    commands:
      - echo "Pushing the Docker image on `date`"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG