version: 0.2
env:
  variables:
    IMAGE: python-flask
    VERSION: 1.0

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
    commands:
      - echo "1. Installing additional tool..."
      - pip3 install pylint
  pre_build:
    on-failure: ABORT
    commands:
      - echo "2. Signing to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo "3. Running static code analysis..."
      - pylint --fail-under=8 app.py

      - echo "4. Building the Docker image..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$VERSION.$CODEBUILD_BUILD_NUMBER -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:latest .
  post_build:
    on-failure: ABORT
    commands:
      - echo "5. Pushing the Docker image to Amazon ECR..."
      - docker push --all-tags $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE

      - echo "6. Generate Docker image information for ECS Task Definition..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$VERSION.$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
artifacts:
    files: imagedefinitions.json