version: 0.2
env:
  variables:
    IMAGE: python-flask
    VERSION: 1.1
    REPOSITORY: 890913392175.dkr.ecr.us-east-1.amazonaws.com

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "1. Logging in to Amazon ECR on `date`"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo "2. Building the Docker image on `date`"
      - docker build -t $IMAGE_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER -t $IMAGE_NAME:latest .
      - echo "3. Execute the Docker image on `date`"
      - docker run -p 8888:8888 --name flask_container -d $IMAGE_NAME:latest
      - sleep 5s
      - echo "4. Testing the Docker container on `date`"
      - TESTING_OUTPUT=$(docker exec -i flask_container curl "http://localhost" | grep -ci "$TESTING_PARAMETER")
      - if [ $TESTING_OUTPUT -eq "0" ]; then exit 1 ; else echo "5. Testing SUCCESSFULLY on `date`" ; fi
    finally:
      - docker images
      - docker ps
  post_build:
    on-failure: ABORT
    commands:
      - echo "6. Pushing the Docker image on `date`"
      - docker push $REPOSITORY/$IMAGE_NAME --all-tags
      - printf '[{"name":$IMAGE_NAME,"imageUri":"%s"}]' $REPOSITORY/$IMAGE_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
    finally:
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json