version: 0.2
env:
  variables:
    IMAGE: python-flask
    VERSION: 1.1
    REPOSITORY: 890913392175.dkr.ecr.us-east-1.amazonaws.com

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "1. Installing dependency..."
      - pip3 install flask
  pre_build:
    on-failure: CONTINUE
    commands:
      - echo "2. Testing started to application..."
      - nohup python3 app.py &
      - curl "http://127.0.0.1:80"
      - export TESTING_OUTPUT=$(curl "http://127.0.0.1:80" | grep -ci "$TESTING_PARAMETER")
      - if [ $TESTING_OUTPUT -eq "0" ]; then exit 1; else echo "3. Testing finished SUCCESSFULLY!"; fi
      - echo "4. Logging in to docker registry using Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY
    finally:
      - echo "TESTING_OUTPUT variable is $TESTING_OUTPUT"
  build:
    on-failure: ABORT
    commands:
      - echo "5. Building the Docker image..."
      - docker build -t $REPOSITORY/$IMAGE:$VERSION.$CODEBUILD_BUILD_NUMBER -t $REPOSITORY/$IMAGE:latest .
      - echo "6. Trying to execute the Docker image..."
      - docker run -p 80:80 --name flask_container -id $REPOSITORY/$IMAGE:latest
    finally:
      - docker images
      - docker ps
  post_build:
    on-failure: ABORT
    commands:
      - echo "7. Pushing the Docker image to Amazon ECR..."
      - docker push --all-tags $REPOSITORY/$IMAGE
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE $REPOSITORY/$IMAGE:$VERSION.$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
artifacts:
    files: imagedefinitions.json